### ISSUE TITLE
create items for curators and evidence codes, update geneprotein

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#109]
scanning the console output from the GOProtein_Bot job currently running (http://jenkins.sulab.org/job/GOProtein_Bot/62/consoleFull) we clearly need to create WD items for a few curators (eg synGO, YuBioLab, ARUK-UCL) and at least one evidence code (HDA).  Mappings should be added to https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/geneprotein/__init__.py.

**Comment by andrawaag** [comment]
I added the mappings for the missing curators:

'PseudoCAP': 'Q60526133',
 'ARUK-UCL': 'Q60526173',
 'GOC-OWL': 'Q60527201',
 'SynGO': 'Q60527231',
 'SynGO-UCL': 'Q60527231',
 'YuBioLab':'Q60527361',
 'JCVI': 'Q1439786',
'Mengo': 'Q60527548',
'PAMGO_GAT': 'Q60527768',
'RGD': 'Q7295410',
'Roslin_Institute': 'Q1633976',
 'TIGR': 'Q1439786'

The pairs  "SynGO and SynGO-UCL" and "JCVI and TIGR" point to identical Wikidata id's. This is because these items were merged in the source.

Also the following evidence codes were added
    'HDA': 'Q60521899',
    'HEP': 'Q60521293'

**Comment by andrewsu** [comment]
addressed in https://github.com/SuLab/scheduled-bots/commit/5cff12d4240f6108fbc0ed5116f746e31e391c18
