### ISSUE TITLE
polish wikidatasparqlexamples README

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#19]
Confirm that they all still execute, that the ones that should return zero results actually return zero, that the ones that should be non-zero are still non-zero, etc.

**Comment by stuppie** [comment]
I think it makes sense to move all of the example sparql queries onto a sub-page of our ProteinBoxBot Wikidata account. See example [here](https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples).

**Pros**
- Each sparql query is written in a [template](https://www.wikidata.org/wiki/Template:SPARQL2) which automatically gives you syntax highlighting, pulls out the items and properties used in the query along with their labels, which makes the query easier to read (as you can see what the IDs mean)
- Because the queries are put into this template, it makes them easily "extractable" from the page (if we want to check them with an external or internal tool)
- There exist tools such as [ListeriaBot](http://magnusmanske.de/wordpress/?p=301) which can automatically run the queries and add the results table to the page (live!). See the [2nd query](https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples#Which_variant_of_which_gene_predicts_a_positive_prognosis_in_colorectal_cancer) for an example.
- We can expand this into a full testing page by: 1) Expand the SPARQL2 template to accept a "validator" argument. 2) Write a Lua module that runs all of the sparql queries within these templates and passes the results to a validator, then updates the page
- Anybody can edit it

**Cons**
- Anybody can edit it

**Comment by andrewsu** [comment]
Pros far outweigh the con, IMO.  Not even sure that con is a con...

**Comment by stuppie** [comment]
Moved all [here](https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples). All execute and return what they claim to return
