### ISSUE TITLE
Disease links to GHD

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#42]
Per email/context from James Heilman below, add links from disease items to GHD.

As a starting point, we need to figure out

- [ ] is there a mapping table available?
- [ ] does a suitable property already exist?

> ---------- Forwarded message ----------
> From: James Heilman 
> Subject: WD help
> To: Andrew Su 
> 
> Hey Andrew
> 
> We have a new classification / external resources link box at the end of articles such as you can see here https://en.wikipedia.org/wiki/Gout#External_links
> 
> Interested in adding some more ELs to WD and wondering if you can help with that? For example wanting to add:
> 
> 1) cdc.gov links for diseases https://www.cdc.gov/az/a.html
> 
> 2) Rare Disease Database https://rarediseases.org/for-patients-and-families/information-resources/rare-disease-information/ (1200 items)
> 
> 3) GARD links https://rarediseases.info.nih.gov/diseases
> 
> 4) GHD https://ghr.nlm.nih.gov/condition
> 
> Will then pull these ELs directly from WD similar to how we are doing it do patients.info Possible?

**Comment by gtsueng** [comment]
This one is readily mapped as the topic list/urls are available as an xml. The API can then be used to pull xrefs (GTR, GeneReviews, ICD-10-CM, MeSH, OMIM, Orphanet, SNOMED CT) for each url; however, there appears to be one-to-many and many-to-one mapping issues with some of these identifiers. The mappings with the fewest issues appear to be mappings to Orphanet which we can use to pull appropriate WDIDs.

Data retrieved from the API includes modes of inheritance which can also be imported to WD.
Test Run of 10 items: 
https://www.wikidata.org/wiki/Q21154055
https://www.wikidata.org/wiki/Q21154058
https://www.wikidata.org/wiki/Q21154076
https://www.wikidata.org/wiki/Q366868
https://www.wikidata.org/wiki/Q4552290
https://www.wikidata.org/wiki/Q21154064
https://www.wikidata.org/wiki/Q21154079
https://www.wikidata.org/wiki/Q209049
https://www.wikidata.org/wiki/Q2692054
https://www.wikidata.org/wiki/Q29982079

**Comment by gtsueng** [comment]
Property proposal here: https://www.wikidata.org/wiki/Wikidata:Property_proposal/Natural_science#Genetics_Home_Reference_Conditions_ID

**Comment by gtsueng** [comment]
In case there are licensing concerns, their [terms of use](https://ghr.nlm.nih.gov/about/terms-and-conditions) specifically states: You may not - Assert proprietary rights to any content on the Genetics Home Reference website that is in the **public domain**.

[It also states](https://ghr.nlm.nih.gov/about) that "All the information on Genetics Home Reference, unless otherwise noted, is written by staff of the National Library of Medicine who have advanced training in genetics and public health, and is reviewed by experts in research and patient care."

And the [NLM copyright](https://www.nlm.nih.gov/copyright.html) page states: "Works produced by the U.S. government are not subject to copyright protection in the United States. Any such works found on National Library of Medicine (NLM) Web sites may be freely used or reproduced without permission in the U.S. Please acknowledge NLM as the source of the information by including the phrase “Courtesy of the U.S. National Library of Medicine” or “Source: U.S. National Library of Medicine.”
