### ISSUE TITLE
Should protein be a Subclass (P279) of an interpro family  or part of (P361)

### ISSUE THREAD

**Issue by andrawaag** [SuLab/GeneWikiCentral#68]
At the bioschemas meeting I have been discussing the protein description in bioschemas. When reviewing a protein record in Wikidata (https://www.wikidata.org/wiki/Q587961) the question why we are using "subclass of (P279)" https://www.wikidata.org/wiki/Q587961#P279  to link to the protein family and not the "part of (P361)" property.

**Comment by stuppie** [comment]
I think the original reason was because when we added these (https://www.wikidata.org/w/index.php?title=Q587961&oldid=351459868), proteins were "subclass of" protein, because that is how some vocal Wikidata volunteers wanted them organized. And so to keep the logical chain, we used subclass of. I could see it using "part of" also, but I don't know how strongly I feel about either. Do they have a compelling reason for "part of" over "subclass" ?

**Comment by andrawaag** [comment]
subclass of suggests inheritance of properties. Apparently, not all properties of an Interpro family also apply to a specific protein.

**Comment by sebotic** [comment]
I agree that part of might make more sense here.

**Comment by stuppie** [comment]
Changing this now. @putmantime Does this affect wikigenomes at all?

**Comment by stuppie** [comment]
This has been implemented and run
